### ISSUE TITLE
When will Python 3 be supported?

### ISSUE THREAD

**Issue by nueverest** [RusticiSoftware/TinCanPython#91]
I'm curious about the timeline for Python 3 support.

**Comment by brianjmiller** [comment]
There isn't one. At the time of development Python 3 adoption was seemingly really poor and it was just too difficult to maintain two code lines for a version that didn't seem to be going anywhere quickly. Having said that we're happy to accept community contributions to get it supported, particularly if we can limit the amount of overhead in supporting both, as I doubt we can just stop supporting the 2.x line.

**Comment by nueverest** [comment]
http://python-future.org/compatible_idioms.html is the best starting point.  For many cases an import statement is all that's required.

**Comment by leveque** [comment]
There's Python 3.5 fork at https://github.com/zachlowry/TinCanPython/tree/python35 that has already asked for a PR

**Comment by brianjmiller** [comment]
Python 3.x support has been merged and tagged as the `1.0.0` release, as well as a new default branch created called `3.x`, support for 2.x will remain on the `2.x` branch but I do not expect there to be any updates there.
