### ISSUE TITLE
how clould i get the statement with python

### ISSUE THREAD

**Issue by chung771026** [RusticiSoftware/TinCanPython#92]
i wanna get the statement by python to analyze the data from LRS. i don't know how to do it.

**Comment by brianjmiller** [comment]
Generally you want to set up an instance of the `RemoteLRS` class and then call the various methods of that instance to communicate with an LRS. If you are trying to get a single statement then you'd want the `retrieve_statement` method. If you are trying to retrieve the stream of statements then you'd generally want the `query_statements` method. The best place to look for sample code is probably the test suite for the library, you can see examples of the above at:

https://github.com/RusticiSoftware/TinCanPython/blob/master/test/remote_lrs_test.py#L61 (setup RemoteLRS object)
https://github.com/RusticiSoftware/TinCanPython/blob/master/test/remote_lrs_test.py#L279 (call retrieve_statement)

**Comment by chung771026** [comment]
thanks your reply. but i encountered another problem. "LRS truncates timestamps which makes returned statements evaluate not equal".how can i fix it.

**Comment by chung771026** [comment]
thanks for your reply. i encounter another problem.

  File "C:\Users\kevin\Anaconda2\lib\unittest\case.py", line 62, in skip_wrapper
    raise SkipTest(reason)
SkipTest: LRS truncates timestamps which makes returned statements evaluate not equal

i want to get statement from LRS. i write the code in main.py. but nothing appear.
maybe utc() is broken?

**Comment by brianjmiller** [comment]
You are pulling in the testing code and using the testing class. That code is just wrapper to make the tests run, and the one you copied in particular gets skipped (on purpose). You just want to use as a sample the code inside of the individual test.

**Comment by chung771026** [comment]
thanks . i use the code to query statement.i got this( tincan.lrs_response.LRSResponse at 0xa778fd0) for my response.
how to make this message to a json object like tincan statement received form lRS?

**Comment by chung771026** [comment]
I fixed it . Thank you very much.
