### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by webdog** [RusticiSoftware/TinCanPython#95]
👋 

Hi there! I noticed there's a [PR](https://github.com/RusticiSoftware/TinCanPython/pull/93) open to support Python 3. Interested in using this library, but would prefer to use Python3.

Could you let me know if there are plans to merge this PR?

Many thanks! ✨

**Comment by benjamid** [comment]
I would second that.  Py3 support for things used to be quite bad, but is quickly becoming de-facto.  At least some significant libraries (e.g., TensorFlow for Windows) only support Py 3 now.

**Comment by escherdragon** [comment]
Any news about this? The PR is over 2 years old now, and Python 3 has become the _de-facto_ standard for new projects (like the one I'm currently working on).

**Comment by brianjmiller** [comment]
Python 3.x support has been merged and tagged as the `1.0.0` release, as well as a new default branch created called `3.x`, support for 2.x will remain on the `2.x` branch but I do not expect there to be any updates there.
