### ISSUE TITLE
Not able to save and retrive the statements

### ISSUE THREAD

**Issue by Prasengupta** [RusticiSoftware/TinCanPython#98]
Hi,

I have changed the Following configuration params from the main.py and ran the script, Below is the exception I'm getting.

constructing the LRS...
...done
constructing the Actor...
...done
constructing the Verb...
...done
constructing the Object...
...done
constructing the Context...
...done
constructing the Statement...
...done
saving the Statement... Traceback (most recent call last):
  File "C:\Python27\myscripts\SVNFOLDER\lRS_Scripiting\main.py", line 86, in <module>
<tincan.lrs_response.LRSResponse object at 0x0000000002F76CF8>
...done
Now, retrieving statement...
    response = lrs.retrieve_statement(response.content.id)
AttributeError: 'NoneType' object has no attribute 'id'

Could you please help me

**Comment by brianjmiller** [comment]
This has been open for more than 2 years, I'm assuming it is no longer active and closing. Please re-open if there is still a question here.
